on: [push, pull_request]

name: CI

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: PHP-CS-Fixer
        uses: OskarStark/php-cs-fixer-ga@2.16.7
        with:
          args: --diff --dry-run --allow-risky yes --stop-on-violation --using-cache=no --path-mode=intersection

  phpstan:
    name: PHPStan Static Analysis
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Composer
        run: composer install
      - env:
          BACKEND: smbclient
        run: php ./vendor/bin/phpstan analyse --level 5 src

  phpunit:
    runs-on: ubuntu-20.04
    name: Unit tests

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: pcov
      - name: Composer
        run: composer install
      - name: PHPUnit Tests
        run: php ./vendor/bin/phpunit tests  -c tests/phpunit.xml --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
